export { createApp } from './app.js'
export { defineComponent } from './component.js'
export { DOM_TYPES, h, hFragment, hSlot, hString } from './h.js'
export { RouterLink, RouterOutlet } from './router-components.js'
export { HashRouter } from './router.js'
export { nextTick } from './scheduler.js'
